# Generated by Django 5.0.4 on 2024-05-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homew', '0002_category_furniture_image_alter_client_privilege_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
