# Generated by Django 5.0.4 on 2024-05-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homew', '0004_furniture_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
