# Generated by Django 5.0.4 on 2024-05-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homew', '0005_alter_furniture_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('url', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
