# Generated by Django 5.0.4 on 2024-05-30 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homew', '0006_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.PositiveIntegerField(verbose_name='Номер заказа')),
                ('date_order', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('date_delivery', models.DateField(verbose_name='Дата доставки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус доставки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homew.client', verbose_name='Клиент')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homew.furniture', verbose_name='Мебель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date_delivery', 'number_order'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(related_name='orders_client', through='homew.Order', to='homew.furniture'),
        ),
    ]
